### ISSUE TITLE
Thoughts on Credential *Issuer*?

### ISSUE THREAD

**Issue by AdamJLemmon** [mattrglobal/oidc-client-bound-assertions-spec#40]
@tplooker Any thoughts on transitioning to the language of *Credential Issuer* instead of Credential Provider?

**Comment by tplooker** [comment]
I could be convinced :) but we called it credential provider as we were trying to draw association to the term IDP (identity provider).

**Comment by AdamJLemmon** [comment]
Yes completely makes sense!  Bridging the worlds...
I will draft some language to propose for the abstract / intro which may help us better determine language to present out.

**Comment by AdamJLemmon** [comment]
Thinking we leave the naming as is for now? Title is Credential Provider but we use the language of issuer / CI as noted through out.
