### ISSUE TITLE
> For instances where implicit flow is used, the response_type of credential SHOULD be used?

### ISSUE THREAD

**Issue by Sakurann** [mattrglobal/oidc-client-bound-assertions-spec#56]
The spec text says in section 2.3
> For instances where implicit flow is used, the response_type of credential SHOULD be used?

when implicit flow is used support for Credential Provider is indicated both by scope = openid & openid_credential and response_type = id_token & credential ?

**Comment by AdamJLemmon** [comment]
@tplooker correct me here... 

but I believe for security purposes implicit should not be supported as these precious credential resources should not be flowing over the front channel.

**Comment by Sakurann** [comment]
I actually think it would be response_type = id_token & token & credential because you also need an access token to take to the credential endpoint, or was that the intention of the credential?

**Comment by AdamJLemmon** [comment]
Nothing needs to change with existing flows, it's just an added scope that grants access to the credential endpoint. 
So all of the hybrid flows would work fine.  
```
scope=openid openid_credential
response_type=code id_token
```

**Comment by Sakurann** [comment]
response_type = id_token & token is implicit flow

**Comment by Sakurann** [comment]
>  it's just an added scope that grants access to the credential endpoint.

exactly why I was trying to understand the rationale behind an additional response_type, which I guess is to get an access token to take to the credential endpoint in which case response_type = id_token & token would be enough

**Comment by AdamJLemmon** [comment]
Yes all those flows are fine... although I think getting the access token over the front channel would be discouraged these days, especially when scoped to access credentials.

We are not suggesting any additional response type, just a scope :)

**Comment by Sakurann** [comment]
> We are not suggesting any additional response type, just a scope :)

got it! "For instances where implicit flow is used, the response_type of credential SHOULD be used" does sound like you are.

**Comment by Sakurann** [comment]
probably the issue should be renamed to "should transporting credentials using implicit flow be allowed?"

**Comment by AdamJLemmon** [comment]
Ah good catch in the doc thanks!

**Comment by AdamJLemmon** [comment]
Odd that line isn't actually in the spec.md as expected: https://github.com/mattrglobal/oidc-client-bound-assertions-spec/blob/master/spec.md#response-types

Will get the doc updated.

**Comment by Sakurann** [comment]
yeah I was looking at this.. thanks! https://mattrglobal.github.io/oidc-client-bound-assertions-spec/

**Comment by tplooker** [comment]
@Sakurann i think we can close this now?

**Comment by Sakurann** [comment]
yes
